# Generated by Django 4.2.7 on 2023-11-05 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(max_length=7, unique=True)),
                ('expiry_time', models.DateField()),
                ('uses_left', models.PositiveIntegerField(default=10)),
                ('status', models.TextField(choices=[('EXP', 'EXPIRED'), ('ACT', 'ACTIVE')], default='ACT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='URLUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shorturl')),
            ],
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_code'], name='api_shortur_short_c_f96590_idx'),
        ),
    ]
